[package]
name = "dioxus-game-of-life"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = "0.3.2"
dioxus-web = "0.3.1"
wasm-bindgen = "0.2.84"
async-std = "1"

[dependencies.web-sys]
version = "0.3.61"
features = [
    'CanvasRenderingContext2d',
    'Document',
    'HtmlCanvasElement',
]
