[application]
name = "dioxus-game-of-life"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "Dioxus game of life"

[web.watcher]
reload_html = true
watch_path = ["src"]

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
